apiVersion: v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
  creationTimestamp: "2020-02-26T07:52:23Z"
  generation: 3
  labels:
    app: hello-world
  name: hello-world
  namespace: default
  resourceVersion: "92571"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/hello-world
  uid: 523b7cbf-9386-4502-a188-9d39efc15967
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: hello-world
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - image: woomun09/node-hello-world:v1.1
        imagePullPolicy: IfNotPresent
        name: node-hello-world
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2020-02-26T07:52:24Z"
    lastUpdateTime: "2020-02-26T07:52:24Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2020-02-26T07:52:23Z"
    lastUpdateTime: "2020-02-26T10:46:27Z"
    message: ReplicaSet "hello-world-66fd6b586" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 3
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
